-- AlterEnum
ALTER TYPE "SetupType" ADD VALUE 'JADU_KI_CHADDI';
ALTER TYPE "SetupType" ADD VALUE 'GOLDEN_LINE';
ALTER TYPE "SetupType" ADD VALUE 'BLACK_BOX';
ALTER TYPE "SetupType" ADD VALUE 'JACKPOT';
ALTER TYPE "SetupType" ADD VALUE 'LAKSHMAN_REKHA';
